---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/golang-release
    tag: 'latest'

inputs:
- name: usn-resource

run:
  path: usn-resource/ci/tasks/test-integration.sh
