---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 'latest'

inputs:
- name: usn-src
  path: gopath/src/github.com/cloudfoundry/usn-resource

run:
  path: gopath/src/github.com/cloudfoundry/usn-resource/ci/tasks/test-integration.sh
