#!/bin/bash

set -eu ; export SHELLOPTS

cd "$(cd "$(dirname "$0")" && pwd)"

export CGO_ENABLED=0
export GOOS=linux
export GOARCH=amd64

docker_dir=$PWD

( cd ..

  go build -o $docker_dir/assets/in in/*
  go build -o $docker_dir/assets/check check/*
  go build -o $docker_dir/assets/out out/*

  git rev-parse HEAD > $docker_dir/assets/version
)
