name: usn-resource

resources:
  - name: usn-resource
    type: git
    source:
      uri: git@github.com:cloudfoundry/usn-resource.git
      branch: master
      private_key: ((github_deploy_key_usn_resource.private_key))

  - name: golang-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-package-golang-release.git

  - name: usn-image
    type: docker-image
    source:
      repository: bosh/usn-resource
      username: ((docker.username))
      password: ((docker.password))

  - name: weekly
    type: time
    source:
      start: 3:00 -0700
      stop: 4:30 -0700
      days: [ Saturday ]

jobs:
  - name: test-integration
    public: true
    plan:
      - get: usn-resource
        trigger: true
      - task: test-integration
        file: usn-resource/ci/tasks/test-integration.yml

  - name: bump-deps
    plan:
    - in_parallel:
      - get: usn-resource
      - get: golang-release
      - get: weekly
        trigger: true
    - task: bump-deps
      file: golang-release/ci/tasks/shared/bump-deps.yml
      input_mapping:
        input_repo: usn-resource
      output_mapping:
        output_repo: bumped-usn-resource
    - task: test-integration
      file: usn-resource/ci/tasks/test-integration.yml
      input_mapping:
        usn-resource: bumped-usn-resource
    - put: usn-resource
      params:
        repository: bumped-usn-resource
        rebase: true

  - name: publish
    plan:
      - get: usn-resource
        passed: [test-integration]
      - task: build
        file: usn-resource/ci/tasks/build.yml
      - put: usn-image
        params:
          build: usn-resource/docker
          dockerfile: usn-resource/docker/Dockerfile
